# Generated by Django 2.2 on 2020-09-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='teams',
            new_name='team',
        ),
    ]
