# Generated by Django 2.2 on 2020-09-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricapp', '0002_auto_20200917_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
