# Generated by Django 2.2 on 2020-09-17 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricapp', '0003_auto_20200917_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stadiums',
            },
        ),
        migrations.AlterField(
            model_name='match',
            name='match_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cricapp.Location'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_stadium',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cricapp.Stadium'),
        ),
    ]
