# Generated by Django 2.2 on 2020-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricapp', '0004_auto_20200917_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_stadium',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Stadium',
        ),
    ]
