# Generated by Django 2.2 on 2020-09-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricapp', '0005_auto_20200917_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='point',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
