# Generated by Django 2.2 on 2020-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricapp', '0008_auto_20200918_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.CharField(max_length=128),
        ),
    ]
