# Generated by Django 2.2 on 2020-09-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricapp', '0009_auto_20200918_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.CharField(max_length=128),
        ),
    ]
